# Generated by Django 5.0.4 on 2024-06-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ovqat nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Ovqat turi',
                'verbose_name_plural': 'Ovqat turlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_child', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Bir bolaga miqdor')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='meals.mealtype', verbose_name='Ovqat turi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Ovqat tarkibi',
                'verbose_name_plural': 'Ovqat tarkiblari',
            },
        ),
        migrations.CreateModel(
            name='MealOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children_count', models.PositiveIntegerField(verbose_name='Bolalar soni')),
                ('buffer_percentage', models.DecimalField(decimal_places=1, default=15.0, max_digits=4, verbose_name='Qo\'shimcha foiz')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Umumiy narx')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('completed', 'Bajarilgan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.mealtype', verbose_name='Ovqat turi')),
            ],
            options={
                'verbose_name': 'Ovqat buyurtmasi',
                'verbose_name_plural': 'Ovqat buyurtmalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
