# Generated by Django 5.0.4 on 2024-06-20 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('general', 'Umumiy'), ('request', 'Talab'), ('suggestion', 'Taklif'), ('complaint', 'Shikoyat'), ('question', 'Savol')], default='general', max_length=20, verbose_name='Xabar turi')),
                ('subject', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('content', models.TextField(verbose_name='Xabar matni')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Shoshilinch')),
                ('is_read', models.BooleanField(default=False, verbose_name='O\'qilgan')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='Javob')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Javob berilgan vaqt')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi')),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_messages', to=settings.AUTH_USER_MODEL, verbose_name='Javob beruvchi')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
