# Generated by Django 5.0.4 on 2024-06-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot nomi')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Litr'), ('dona', 'Dona'), ('paket', 'Paket')], max_length=10, verbose_name='O\'lchov birligi')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zaxira miqdori')),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimal zaxira darajasi')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Birlik narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['name'],
            },
        ),
    ]
